### ISSUE TITLE
Servo stops responding after connecting via ttyS0

### ISSUE THREAD

**Issue by zas9vf** [sbcshop/PiArm#1]
I've been having an issue with setting up my PiArm. The LEDs on all servos blink normally when the Pi is on but the second I connect to it via ttyS0, a few of the servos start flashing red and stop responding. I notice that this happens when I use the Config or the Control GUIs. It works with the joystick sometimes but every now and then a few servos go flashing red and stop responding all together. Is there anyone I could contact for some support?

Thanks in advance

**Comment by sbcshop** [comment]
Hello,

The servo motor working voltage is 6-8.4V. If you connect power supply less than 6V than RED led will start blinking in the servo motor. This indicates that the power supply is not as per the required voltages.
For support, you can contact us at support@sb-components.co.uk

Regards,
SB Team
